dbt_transformation_layer:
  outputs:
    dev:
      account: ARWIGJK-UW46260
      database: IGDB
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      role: TRANSFORM
      schema: SILVER
      threads: 1
      type: snowflake
      user: DBT
      warehouse: COMPUTE_WH
  target: dev
