
USE ROLE SECURITYADMIN;
USE WAREHOUSE COMPUTE_WH;


CREATE ROLE IF NOT EXISTS TRANSFORM;
GRANT ROLE TRANSFORM TO ROLE SECURITYADMIN;


CREATE USER IF NOT EXISTS dbt
    LOGIN_NAME = 'dbt'
    TYPE = 'SERVICE'
    RSA_PUBLIC_KEY = "<PUBIC_KEY>"          -- Omitted due to security reasons
    DEFAULT_ROLE = TRANSFORM
    COMMENT = 'Service user that can be used with dbt.'
;

GRANT ROLE TRANSFORM TO USER dbt;


-- Permissions for the role:
GRANT USAGE, OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE TRANSFORM;

GRANT USAGE, CREATE SCHEMA ON DATABASE IGDB TO ROLE TRANSFORM;
GRANT USAGE ON ALL SCHEMAS IN DATABASE IGDB TO ROLE TRANSFORM;
GRANT USAGE, CREATE TABLE, CREATE VIEW, MODIFY ON FUTURE SCHEMAS IN DATABASE IGDB TO ROLE TRANSFORM;


GRANT SELECT ON ALL TABLES IN SCHEMA IGDB.BRONZE TO ROLE TRANSFORM;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA IGDB.BRONZE TO ROLE TRANSFORM;
GRANT SELECT ON ALL VIEWS IN SCHEMA IGDB.BRONZE TO ROLE TRANSFORM;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE VIEWS IN SCHEMA IGDB.BRONZE TO ROLE TRANSFORM;