USE ROLE SECURITYADMIN;
USE WAREHOUSE COMPUTE_WH;


CREATE ROLE IF NOT EXISTS REPORTING;
GRANT ROLE REPORTING TO ROLE SECURITYADMIN;


CREATE USER IF NOT EXISTS POWERBI
    LOGIN_NAME = 'power_bi'
    TYPE = 'SERVICE'
    RSA_PUBLIC_KEY = '<PUBLIC_KEY>'  -- Omitted due to security reasons
    DEFAULT_ROLE = REPORTING
    COMMENT = 'Read-only service user for Power BI reporting on IGDB.GOLD'
;

GRANT ROLE REPORTING TO USER POWERBI;


-- Permissions for the role:
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE REPORTING;

GRANT USAGE ON DATABASE IGDB TO ROLE REPORTING;
GRANT USAGE ON SCHEMA IGDB.GOLD TO ROLE REPORTING;

GRANT SELECT ON ALL TABLES IN SCHEMA IGDB.GOLD TO ROLE REPORTING;
GRANT SELECT ON ALL VIEWS IN SCHEMA IGDB.GOLD TO ROLE REPORTING;

GRANT SELECT ON FUTURE TABLES IN SCHEMA IGDB.GOLD TO ROLE REPORTING;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA IGDB.GOLD TO ROLE REPORTING;